#!/usr/bin/env python3
"""
Seed the database with vocabulary, grammar topics, and stories from JSON files.
Run from the backend/ directory with the venv activated:
    .venv/bin/python scripts/seed_content.py
"""
import sys
import json
from pathlib import Path

# Allow running from backend/ directory
sys.path.insert(0, str(Path(__file__).parent.parent))

from app.core.config import settings
from app.db.session import SessionLocal, engine
from app.db import models

DATA_DIR = settings.DATA_DIR


def seed_vocabulary(db):
    count = 0
    for json_file in (DATA_DIR / "vocabulary").glob("*.json"):
        if json_file.stat().st_size == 0:
            print(f"  Skipping empty file: {json_file.name}")
            continue
        with open(json_file) as f:
            words = json.load(f)
        for w in words:
            existing = db.query(models.VocabularyItem).filter_by(
                dutch_word=w["dutch_word"], level=w["level"]
            ).first()
            if not existing:
                item = models.VocabularyItem(**{
                    k: v for k, v in w.items()
                    if hasattr(models.VocabularyItem, k)
                })
                db.add(item)
                count += 1
    db.commit()
    print(f"  Vocabulary: {count} new items seeded")

def seed_stories(db):
    count = 0
    for json_file in (DATA_DIR / "stories").glob("*.json"):
        if json_file.stat().st_size == 0:
            print(f"  Skipping empty file: {json_file.name}")
            continue
        with open(json_file) as f:
            stories = json.load(f)
        for s in stories:
            existing = db.query(models.Story).filter_by(slug=s["slug"]).first()
            if not existing:
                story = models.Story(**{
                    k: v for k, v in s.items()
                    if hasattr(models.Story, k)
                })
                db.add(story)
                count += 1
    db.commit()
    print(f"  Stories: {count} new stories seeded")


def seed_grammar(db):
    count = 0
    grammar_dir = DATA_DIR / "grammar"
    if not grammar_dir.exists():
        return
    for json_file in grammar_dir.glob("*.json"):
        if json_file.stat().st_size == 0:
            print(f"  Skipping empty file: {json_file.name}")
            continue
        with open(json_file) as f:
            topics = json.load(f)
        for t in topics:
            existing = db.query(models.GrammarTopic).filter_by(slug=t["slug"]).first()
            if not existing:
                topic = models.GrammarTopic(**{
                    k: v for k, v in t.items()
                    if hasattr(models.GrammarTopic, k)
                })
                db.add(topic)
                count += 1
    db.commit()
    print(f"  Grammar: {count} new topics seeded")


# License hygiene (handoff Part A): regenerate ATTRIBUTIONS.md from the
# source/license/attribution columns on every seed run.
_LICENSE_NOTES = {
    "tatoeba": "Tatoeba (CC BY 2.0 FR) — per-sentence attribution required",
    "wiktionary": "Wiktionary via wiktextract/kaikki.org (CC BY-SA 3.0 + GFDL)",
    "nt2lex": "NT2Lex (CC BY-NC-SA 4.0) — non-commercial use only",
    "wikibooks": "Wikibooks Dutch (CC BY-SA)",
    "open-knm": "Open KNM vocabulary (open source, community-driven)",
    "common-voice": "Mozilla Common Voice (CC0)",
}


def write_attributions(db):
    rows: list[tuple[str, str, str]] = []
    for model in (models.VocabularyItem, models.Story, models.GrammarTopic):
        for item in db.query(model).filter(model.attribution.isnot(None)).all():
            label = getattr(item, "dutch_word", None) or getattr(item, "slug", "?")
            rows.append((model.__tablename__, label, item.attribution))

    path = DATA_DIR.parent / "ATTRIBUTIONS.md"
    with open(path, "w") as f:
        f.write("# Attributions\n\n")
        f.write("Generated by `scripts/seed_content.py` — do not edit by hand.\n\n")
        f.write("## Source licenses\n\n")
        for note in _LICENSE_NOTES.values():
            f.write(f"- {note}\n")
        f.write("\n## Per-item attributions\n\n")
        if not rows:
            f.write("_No externally-sourced content seeded yet._\n")
        for table, label, attribution in sorted(rows):
            f.write(f"- `{table}` · {label}: {attribution}\n")
    print(f"  Attributions: {len(rows)} entries → {path}")


def main():
    print("Creating tables…")
    models.Base.metadata.create_all(bind=engine)
    print("Seeding database…")
    db = SessionLocal()
    try:
        seed_vocabulary(db)
        seed_grammar(db)
        seed_stories(db)
        write_attributions(db)
        print("Done.")
    finally:
        db.close()


if __name__ == "__main__":
    main()
