"""
Idempotent content seeding from the data/ JSON files.

Shared by the startup hook, the background scheduler, and
scripts/seed_content.py — content lands in the DB without manual steps.
"""
import json
import logging
from pathlib import Path

from sqlalchemy.orm import Session

from app.core.config import settings
from app.db import models

logger = logging.getLogger(__name__)


def _load_json_array(path: Path) -> list[dict]:
    if path.stat().st_size == 0:
        return []
    return json.loads(path.read_text(encoding="utf-8"))


def seed_vocabulary(db: Session) -> int:
    count = 0
    vocab_dir = settings.DATA_DIR / "vocabulary"
    if not vocab_dir.exists():
        return 0
    for json_file in vocab_dir.glob("*.json"):
        for w in _load_json_array(json_file):
            existing = db.query(models.VocabularyItem).filter_by(
                dutch_word=w["dutch_word"], level=w["level"]
            ).first()
            if not existing:
                db.add(models.VocabularyItem(**{
                    k: v for k, v in w.items() if hasattr(models.VocabularyItem, k)
                }))
                count += 1
    db.commit()
    return count


def seed_grammar(db: Session) -> int:
    count = 0
    grammar_dir = settings.DATA_DIR / "grammar"
    if not grammar_dir.exists():
        return 0
    for json_file in grammar_dir.glob("*.json"):
        for t in _load_json_array(json_file):
            existing = db.query(models.GrammarTopic).filter_by(slug=t["slug"]).first()
            if not existing:
                db.add(models.GrammarTopic(**{
                    k: v for k, v in t.items() if hasattr(models.GrammarTopic, k)
                }))
                count += 1
    db.commit()
    return count


def seed_stories(db: Session) -> int:
    count = 0
    stories_dir = settings.DATA_DIR / "stories"
    if not stories_dir.exists():
        return 0
    for json_file in stories_dir.glob("*.json"):
        for s in _load_json_array(json_file):
            existing = db.query(models.Story).filter_by(slug=s["slug"]).first()
            if not existing:
                db.add(models.Story(**{
                    k: v for k, v in s.items() if hasattr(models.Story, k)
                }))
                count += 1
    db.commit()
    return count


# License hygiene (handoff Part A): regenerate ATTRIBUTIONS.md from the
# source/license/attribution columns on every seed run.
_LICENSE_NOTES = {
    "tatoeba": "Tatoeba (CC BY 2.0 FR) — per-sentence attribution required",
    "wiktionary": "Wiktionary via wiktextract/kaikki.org (CC BY-SA 3.0 + GFDL)",
    "nt2lex": "NT2Lex (CC BY-NC-SA 4.0) — non-commercial use only",
    "wikibooks": "Wikibooks Dutch (CC BY-SA)",
    "open-knm": "Open KNM vocabulary (open source, community-driven)",
    "common-voice": "Mozilla Common Voice (CC0)",
}


def write_attributions(db: Session) -> int:
    rows: list[tuple[str, str, str]] = []
    for model in (models.VocabularyItem, models.Story, models.GrammarTopic):
        for item in db.query(model).filter(model.attribution.isnot(None)).all():
            label = getattr(item, "dutch_word", None) or getattr(item, "slug", "?")
            rows.append((model.__tablename__, label, item.attribution))

    path = settings.DATA_DIR.parent / "ATTRIBUTIONS.md"
    with open(path, "w") as f:
        f.write("# Attributions\n\n")
        f.write("Generated by the seed job — do not edit by hand.\n\n")
        f.write("## Source licenses\n\n")
        for note in _LICENSE_NOTES.values():
            f.write(f"- {note}\n")
        f.write("\n## Per-item attributions\n\n")
        if not rows:
            f.write("_No externally-sourced content seeded yet._\n")
        for table, label, attribution in sorted(rows):
            f.write(f"- `{table}` · {label}: {attribution}\n")
    return len(rows)


def seed_all(db: Session) -> str:
    """Run all seeders; returns a human-readable summary."""
    vocab = seed_vocabulary(db)
    grammar = seed_grammar(db)
    stories = seed_stories(db)
    attributions = write_attributions(db)
    summary = (
        f"{vocab} vocab, {grammar} grammar, {stories} stories seeded; "
        f"{attributions} attribution entries"
    )
    logger.info("seed_all: %s", summary)
    return summary
