"""add_uq_vocab_word_level

Revision ID: c3879087f590
Revises: 
Create Date: 2026-04-11 00:04:33.423884

"""
from alembic import op
import sqlalchemy as sa


revision = 'c3879087f590'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_vocab_word_level', 'vocabulary_items', ['dutch_word', 'level'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_vocab_word_level', 'vocabulary_items', type_='unique')
    # ### end Alembic commands ###
